### ISSUE TITLE
Dependency conflict between radboud-el and xrenner

### ISSUE THREAD

**Issue by agolo-alan-hogue** [ad-freiburg/elevant#6]
Trying to install without docker by doing docker file commands as instructed.

There is a conflict apparently between these packages. I managed to get it to run by removing the version requirements, but I don't know if this will actually work or not.

`python3 -m pip install -r requirements.txt`

```
INFO: pip is looking at multiple versions of xrenner to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r requirements.txt (line 11) and -r requirements.txt (line 12) because these package versions have conflicting dependencies.

The conflict is caused by:
    radboud-el 0.0.1 depends on flair>=0.11
    xrenner 2.2.0.0 depends on flair==0.6.1

```

**Comment by agolo-alan-hogue** [comment]
Thank you! Leaving out xrenner did work for now. However, I would like to have the option of using coref in the future, though it's not critical right now. Is there a chance that neuralcoref might be replaced with something like https://github.com/shon-otmazgin/fastcoref, or that it could be included as an option? Fastcoref seems to be pretty standard these days, and seems to be actively maintained.

**Comment by flackbash** [comment]
That looks really good at first glance, thanks for the link. I'll definitely look at adding support for it in ELEVANT.

**Comment by flackbash** [comment]
I removed support for xrenner and added support for fastcoref. You can test it e.g. in combination with ReFinED on our benchmark Wiki-Fair which contains coreference ground truth mentions:
 
```
python3 link_benchmark_entities.py refined.fastcoref -l refined -coref fastcoref -b wiki-fair
```

Note that you cannot use a coreference linker in isolation (without specifying an entity linker), since ELEVANT evaluates the linked entities, not the coreference clusters themselves.
