### ISSUE TITLE
Benchmark conversion from NIF format producing incorrect results

### ISSUE THREAD

**Issue by agolo-alan-hogue** [ad-freiburg/elevant#8]
Hello!

I have a new benchmark based on a small dataset I've put together. It exists in json files natively. I ran a script of my own to convert it to NIF format. I spot checked the NIF file and it looks correct. Specifically, all the entities are linked to the correct texts.

I then ran:

`python3 add_benchmark.py "agolo-e2e-eval" -bfile agolo_e2e_eval_dataset.nif -bformat nif`

After checking the resulting file, it appears that the entities are appearing with the wrong texts. For instance, this is doc16 in the NIF file:

```
<http://example.org/doc16> a nif:Context,
        nif:OffsetBasedString ;
    nif:beginIndex "0"^^xsd:nonNegativeInteger ;
    nif:endIndex "447"^^xsd:nonNegativeInteger ;
    nif:isString """Honduras President Xiomara Castro
```

...and here is the entry for the entity "Honduras":

```
<http://example.org/doc16#offset_0_447_14> a nif:OffsetBasedString,
        nif:Phrase ;
    nif:anchorOf "Honduras " ;
    nif:beginIndex "0"^^xsd:nonNegativeInteger ;
    nif:endIndex "9"^^xsd:nonNegativeInteger ;
    nif:referenceContext <http://example.org/doc16> ;
    itsrdf:taIdentRef <Q30081060> .
```

However, in the resulting file `agolo-e2e-eval.benchmark.jsonl` I see the entity:

`"evaluation_span": [0, 2357], "labels": [{"id": 0, "span": [0, 8], "entity_id": "Q783", "name": "Honduras", "parent": null, "children": [1], "optional": false, "type": "Q27096213|Q43229"},`

in the same record (on the same line) as this text:

`{"id": 21, "title": "http://example.org/doc7", "text": "A helicopter accident in...`

So somehow it appears the conversion script is mixing up the texts and the entities that go with them. This seems to be consistent across the resulting file.

I have attached the input and output files.

Any idea what could be going wrong?

Thanks!

**Comment by agolo-alan-hogue** [comment]
Hm, looks like I this may have been my fault, so I'll close this now. Please disregard.

**Comment by flackbash** [comment]
Alright, let me know if it turns out to have not been an issue on your side :)
